skip_commits:
  message: /((Create.*\.md)|(Update.*\.md))/

version: 0.2.1.{build}

configuration: Release

environment:
  sourcesFolder: src
  solutionName: photosphere-di.sln
  projectName: Photosphere.DependencyInjection

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - cd %sourcesFolder%
  - nuget restore
  - cd ..
  - ps: $nuspecPath = "$env:APPVEYOR_BUILD_FOLDER\$env:sourcesFolder\$env:projectName\$env:projectName.nuspec"
  - ps: $nuspec = [xml](Get-Content $nuspecPath)
  - ps: $nuspec.package.metadata.version = $env:APPVEYOR_BUILD_VERSION
  - ps: $nuspec.Save($nuspecPath)

build:
  verbosity: minimal  
  project: $(sourcesFolder)\$(solutionName)
  publish_nuget: true
  publish_nuget_symbols: true
  
artifacts:
  - path: $(sourcesFolder)\$(projectName)\bin\$(configuration)\
    name: $(projectName)-v$(APPVEYOR_BUILD_VERSION)

deploy:
  - provider: NuGet
    server: https://www.nuget.org
    api_key:
      secure: ddglAApbf5fja6dAaDstiBmewHSQ09BHjeLiQpA/WVvyTaSBmARSdH3xOjlAzkcQ
    skip_symbols: false
    symbol_server: nuget.smbsrc.net
    artifact: $(projectName).$(APPVEYOR_BUILD_VERSION).nupkg
